apiVersion: apps/v1
kind: Deployment
metadata: 
  name: bug-report-frontend-depl
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 1
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: juanpablosaladino/bug-report-frontend:0.5
---
apiVersion: v1
kind: Service
metadata:
  name: bug-report-frontend-srv
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - name: bug-report-frontend
      port: 3000
      targetPort: 3000
